import type { ReactNode } from 'react';
import { Link } from 'react-router';
import { PageHeader } from '@/components/layout/PageHeader';
import { SiteFooter } from '@/components/layout/SiteFooter';

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="font-display text-lg font-semibold">{title}</h2>
      <div className="flex flex-col gap-2 text-text-secondary">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="flex flex-col gap-8">
      <PageHeader
        eyebrow="The fine print"
        title="Terms of Service"
        description="Plain language, kept short — the whole deal in one read. Last updated August 11, 2026."
      />

      <div className="flex max-w-3xl flex-col gap-8">
        <Section title="The service">
          <p>
            Coffee Grinder is an AI job-matching tool: you upload a résumé, we screen job postings
            against it and produce scorecards, gap lists, and draft cover letters. It's an
            early-stage beta run by an independent developer. Features may change, break, or go
            away — we'll try to be graceful about it, but this is a small operation, not an
            enterprise SLA.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            Sign up with a real email you control. Keep your password to yourself; what happens
            under your account is on you. One account per person — the free tier is per-account,
            and gaming it with duplicates is the fastest way to lose access.
          </p>
        </Section>

        <Section title="Free tier and limits">
          <p>
            Every account gets 5 free runs per month, up to 5 postings per run. There's also a
            site-wide daily cap shared by all users — when it's hit, runs resume the next day.
            Limits may change as we learn what the service costs to run; the run-setup screen
            shows your current allowance.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>Keep it simple:</p>
          <ul className="list-disc pl-5">
            <li>Upload only your own résumé, or one you have permission to use.</li>
            <li>No bots, scripts, or scraping — the service is for humans hunting jobs.</li>
            <li>Don't probe, overload, or abuse the service.</li>
            <li>Nothing unlawful.</li>
          </ul>
        </Section>

        <Section title="AI-generated content">
          <p>
            Scores, verdicts, reasoning, and cover-letter drafts are generated by AI. They can be
            wrong, incomplete, or miss context — that's exactly why every claim ships with its
            evidence. Read the receipts before relying on a score, and always review a cover
            letter before sending it. Coffee Grinder is not career, legal, or hiring advice.
          </p>
        </Section>

        <Section title="Job postings">
          <p>
            Postings are fetched from public job boards and belong to their respective owners.
            Apply links take you to third-party sites we don't control.
          </p>
        </Section>

        <Section title="No warranty">
          <p>
            The service is provided as-is and as-available, free of charge, with no warranties of
            any kind. To the maximum extent the law allows, we're not liable for damages arising
            from your use of the service — including decisions made based on AI-generated scores.
          </p>
        </Section>

        <Section title="Ending things">
          <p>
            You can stop using Coffee Grinder anytime and ask for your data to be deleted (
            <Link to="/privacy" className="underline hover:text-text">
              see the Privacy Policy
            </Link>
            ). We can suspend or close accounts that break these terms.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            We may update these terms as the service evolves. The "last updated" date above
            changes when we do; using the service after that means the new terms apply.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Coffee Grinder is a small, independently run beta and doesn't have a public contact
            address yet — one is coming. Until then, the fastest route for questions or requests
            is the person who shared the site with you.
          </p>
        </Section>
      </div>

      <SiteFooter />
    </div>
  );
}
